### PR TITLE
Fix convert function omitting the last part of a text

### PR DESCRIPTION
**Pull request by bebax**
Fix for #99 . I have refactored the *convert* function in the *kakasi* class to append the last result of a text conversion.

### CODE REVIEW

**Comment by miurahr** [comment]
Could you add test case of #99 in tests/test_pykakasi_structured.py  ?

**Comment by bebax** [comment]
Thank you @miurahr for looking at this pull request so quickly! The test cases should have caught #99, however, there is a bug in the test. When the result of a conversion is empty, the test passes even though the result doesn't match the expected values.

I have added a fix for that to tests/test_pykakasi_structured.py. However, this uncovered another, existing bug related to the long vowel mark (_LONG_SYMBOL). How would you suggest to proceed?

**Comment by miurahr** [comment]
I'm now working to fix CI and coverage.
Could you rebase or merge current master and push again?  I believe current master is fixed about gihtub actions script.

There is still an issue on coveralls but please ignore it.

**Comment by bebax** [comment]
I did a rebase. But I think the test fails because at the moment, the new api doesn't handle long vowel marks. For example, "てんさーふろ" converts to "tensaーfuroー" but should be "tensaafuroo". Should I remove that test case for now and open a new issue?

**Comment by bebax** [comment]
I have added handling for the for prolonged sound marks to the new api and all tests pass.

**Comment by miurahr** [comment]
Thank you!

**Pull request merged**
